### ISSUE TITLE
Don't block IP, but add to /var/log/urbackup-ban.log

### ISSUE THREAD

**Issue by Dmitrius7** [Charlymd/URB_Fail2ban#1]
Hi!

Don't block IP, but add to /var/log/urbackup-ban.log
I use UFW firewall. 

How to fix?

Thank you in advance!

**Comment by Charlymd** [comment]
Hi Dmitrius,

this is a first filtering test with IPTable and fail2ban
I will check the functioning of UFW as soon as I have some availability

**Comment by Dmitrius7** [comment]
Thank you! I'll be waiting.

**Comment by Charlymd** [comment]
my default action was to only log for dry test
if you comment this specific "banaction line", default banaction become active
by default it's "iptable-multiport ban"

**Comment by Charlymd** [comment]
For UFW, just add this line in /etc/fail2ban/jail.local and reload fail2ban

_[DEFAULT]
banaction=ufw_

Can you tell me about your implementation ?

**Comment by Charlymd** [comment]
with this directive, fail2ban use this action ban template : 
_actionban = [ -n "<application>" ] && app="app <application>"
            ufw insert <insertpos> <blocktype> from <ip> to <destination> $app_

with default value : 
insertpos = 1
blocktype = reject
destination = any

for UFW application list : 
_sudo ufw app list_

**Comment by Charlymd** [comment]
Hi Dmitrius,

I added new action/jail files for UFW
can you make a try with it ?

**Comment by Dmitrius7** [comment]
Hi!

I'm sorry for the long response.

I tried your new version. For UFW it still doesn't work, it add rule to UFW but I sill have access.
I modifyed it. Now it works fine! Code:


```
###/etc/fail2ban/action.d/urbackup-ufw.conf
...
actionban = ufw insert 1 reject from <ip> to any
actionunban = ufw delete reject from <ip> to any

```

**File** /etc/fail2ban/jail.d/urbackup.conf **attached**
[action.d_urbackup-ufw.zip](https://github.com/Charlymd/URB_Fail2ban/files/4777083/action.d_urbackup-ufw.zip)



**It would be great to add to the README.md :**
- If you use **iptables** copy only one file action.d/urbackup.conf
- If you use **UFW** copy only one file action.d/urbackup-ufw.conf


I created [Pre and post backup scripts template for UrBackup client](https://github.com/Dmitrius7/UrBackup_client_pre_post_backup_scripts_template). Maybe it would be useful for you!

**Thank you for your work!**

**Comment by Dmitrius7** [comment]
I created more simple config files. Now you don't have to make a choise which config files to use (UFW or iptables). Now all in 2 files and they are universal as for ufw and iptables.

Attached [URB_Fail2ban-14062020-0035.zip](https://github.com/Charlymd/URB_Fail2ban/files/4777246/URB_Fail2ban-14062020-0035.zip)

**Comment by Charlymd** [comment]
Ok I have added your code
Next time, you can add your own code and  make a pull request

**Comment by Dmitrius7** [comment]
Ok. Thank you!

I close this issue.
